import './globals.css'
import NavBar from "@/app/components/NavBar";
import {ReactNode} from "react";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: { children: ReactNode }) {
    return (
        <html lang="en">
        <body className='bg-slate-800'>
        <NavBar/>
        {children}
        </body>
        </html>
    )
}
